# Generated by Django 3.2.8 on 2021-10-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chinchilla',
            old_name='breed',
            new_name='color',
        ),
    ]
